sudo: false
before_script:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION}; fi;
    - composer install
    - mysql -e 'create database phinx_testing;'
    - psql -c 'create database phinx_testing;' -U postgres
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
addons:
  postgresql: "9.2"
env:
  - TESTS_PHINX_DB_ADAPTER_POSTGRES_ENABLED=true
script:
    - phpunit --coverage-text --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
matrix:
    exclude:
        - php: hhvm
          env: TESTS_PHINX_DB_ADAPTER_POSTGRES_ENABLED=true
    include:
        - php: 5.4
          env: SYMFONY_VERSION='~2.8'
        - php: hhvm
          env: TESTS_PHINX_DB_ADAPTER_POSTGRES_ENABLED=false
    allow_failures:
        - php: hhvm
